remote_theme: jamesloyys/flexible-jekyll

# Author Settings
author: James Loy # add your name
author-img: james.jpg # add your photo
about-author: Data Scientist from Singapore. Writes about machine learning and deep learning in a visual manner. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: jamesloyys # add your Github handle
social-linkedin: jamesloy1/ # add your Linkedin handle
social-email: # add your Email address

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
